services:
  api_java:
    build:
      context: .
      dockerfile: Transactions/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    network_mode: host

  mysql:
    image: mysql:8.0.32
    environment:
      MYSQL_ROOT_PASSWORD: root
    network_mode: host
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--host=127.0.0.1", "--user=root", "--password=root"]
      interval: 30s
      retries: 5
      timeout: 10s
      start_period: 30s

  api_dotnet:
    build:
      context: .
      dockerfile: API-Bank/API-Bank/Dockerfile
    ports:
      - "5000:8080"
    depends_on:
      mysql:
        condition: service_healthy
    network_mode: host
    entrypoint: ["sh", "-c", "cd src/API-Bank.Infra.Data/ && dotnet ef database update && cd .. && cd .. && dotnet API-Bank.dll"]